version: "2"
services:
  database:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_DATABASE: "reservations"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  reservations:
    restart: always
    build: .
    depends_on:
      - 'database'
    ports:
      - '3001:3001'
    command: bash -c "./wait-for-it.sh database:3306 && npm run seed && npm run start"